app = "arkyn-logs"
primary_region = "gru"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services.http_checks]]
  path = "/nginx-health"
  interval = "10s"
  timeout = "2s"
  grace_period = "10s"
  method = "GET"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
